"""added do not call

Revision ID: 08cfd9ef4e32
Revises: fa53fe066885
Create Date: 2024-07-12 12:49:03.395631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cfd9ef4e32'
down_revision = 'fa53fe066885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('do_not_call', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('do_not_call')

    # ### end Alembic commands ###
