"""add session calculated fields

Revision ID: 42a0a1878f2d
Revises: 30ea50daddbd
Create Date: 2024-07-04 14:35:34.729140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a0a1878f2d'
down_revision = '30ea50daddbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_student_count', sa.Integer(), nullable=True))
        batch_op.drop_column('student_count')
        batch_op.drop_column('volunteer_count')
        batch_op.drop_column('participant_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_count', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('volunteer_count', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('student_count', sa.INTEGER(), nullable=False))
        batch_op.drop_column('manual_student_count')

    # ### end Alembic commands ###
