"""Inital Migration

Revision ID: 488a911e639a
Revises: 
Create Date: 2024-07-03 07:05:55.871743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488a911e639a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('primary_phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('primary_phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('primary_phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('primary_phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
