"""add add end_time and made dlivery calc field

Revision ID: 85a4bfbe1ff6
Revises: 42a0a1878f2d
Create Date: 2024-07-04 14:43:11.626447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a4bfbe1ff6'
down_revision = '42a0a1878f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=False))
        batch_op.drop_column('delivery_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_hours', sa.NUMERIC(), nullable=False))
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
