"""added connector_active_sub

Revision ID: bcc96f1e9e69
Revises: 08cfd9ef4e32
Create Date: 2024-07-12 12:53:44.140092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc96f1e9e69'
down_revision = '08cfd9ef4e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connector_active_subscription', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('connector_active_subscription')

    # ### end Alembic commands ###
